import type { Medicine, SaleRecord, Expense } from "./types";
import { generateId, nowISO, todayISO } from "./utils";
import { STORAGE_KEYS } from "./constants";

const medicines: Medicine[] = [
  {
    id: generateId(),
    name: "Panadol",
    genericName: "Paracetamol",
    batchNumber: "PCM-2024-001",
    expiryDate: "2026-12-31",
    quantity: 150,
    costPrice: 8,
    salePrice: 12,
    supplier: "GSK Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Augmentin",
    genericName: "Amoxicillin + Clavulanate",
    batchNumber: "AUG-2024-002",
    expiryDate: "2025-08-15",
    quantity: 45,
    costPrice: 180,
    salePrice: 230,
    supplier: "GSK Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Brufen",
    genericName: "Ibuprofen",
    batchNumber: "IBU-2024-003",
    expiryDate: "2026-06-30",
    quantity: 8,
    costPrice: 15,
    salePrice: 22,
    supplier: "Abbott Laboratories",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Risek",
    genericName: "Omeprazole",
    batchNumber: "OME-2024-004",
    expiryDate: "2026-09-30",
    quantity: 60,
    costPrice: 55,
    salePrice: 75,
    supplier: "Searle Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Flagyl",
    genericName: "Metronidazole",
    batchNumber: "MET-2024-005",
    expiryDate: "2025-05-20",
    quantity: 5,
    costPrice: 20,
    salePrice: 30,
    supplier: "Sanofi Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Calpol",
    genericName: "Paracetamol Syrup",
    batchNumber: "CAL-2024-006",
    expiryDate: "2026-11-30",
    quantity: 35,
    costPrice: 45,
    salePrice: 60,
    supplier: "GSK Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Cipro",
    genericName: "Ciprofloxacin",
    batchNumber: "CIP-2024-007",
    expiryDate: "2026-03-31",
    quantity: 3,
    costPrice: 90,
    salePrice: 120,
    supplier: "Bayer Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Nexium",
    genericName: "Esomeprazole",
    batchNumber: "ESO-2024-008",
    expiryDate: "2027-01-31",
    quantity: 28,
    costPrice: 140,
    salePrice: 190,
    supplier: "AstraZeneca Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Glucophage",
    genericName: "Metformin",
    batchNumber: "MET-2024-009",
    expiryDate: "2026-10-31",
    quantity: 70,
    costPrice: 30,
    salePrice: 42,
    supplier: "Merck Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Clarinase",
    genericName: "Loratadine + Pseudoephedrine",
    batchNumber: "CLR-2024-010",
    expiryDate: "2025-07-31",
    quantity: 18,
    costPrice: 110,
    salePrice: 155,
    supplier: "Schering-Plough",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Voltaren",
    genericName: "Diclofenac",
    batchNumber: "DIC-2024-011",
    expiryDate: "2026-08-31",
    quantity: 0,
    costPrice: 40,
    salePrice: 58,
    supplier: "Novartis Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Amoxil",
    genericName: "Amoxicillin",
    batchNumber: "AMX-2024-012",
    expiryDate: "2026-05-31",
    quantity: 55,
    costPrice: 50,
    salePrice: 70,
    supplier: "GSK Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Lipitor",
    genericName: "Atorvastatin",
    batchNumber: "ATV-2024-013",
    expiryDate: "2027-03-31",
    quantity: 40,
    costPrice: 120,
    salePrice: 165,
    supplier: "Pfizer Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Norilet",
    genericName: "Norfloxacin",
    batchNumber: "NOR-2024-014",
    expiryDate: "2025-06-30",
    quantity: 7,
    costPrice: 35,
    salePrice: 50,
    supplier: "Sami Pharmaceuticals",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Folic Acid",
    genericName: "Folic Acid 5mg",
    batchNumber: "FOL-2024-015",
    expiryDate: "2026-12-31",
    quantity: 200,
    costPrice: 2,
    salePrice: 5,
    supplier: "Martin Dow",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Ventolin",
    genericName: "Salbutamol",
    batchNumber: "SAL-2024-016",
    expiryDate: "2026-07-31",
    quantity: 22,
    costPrice: 95,
    salePrice: 130,
    supplier: "GSK Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Cefspan",
    genericName: "Cefixime",
    batchNumber: "CEF-2024-017",
    expiryDate: "2025-09-30",
    quantity: 6,
    costPrice: 160,
    salePrice: 220,
    supplier: "Sami Pharmaceuticals",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Rosuvas",
    genericName: "Rosuvastatin",
    batchNumber: "ROS-2024-018",
    expiryDate: "2027-02-28",
    quantity: 33,
    costPrice: 200,
    salePrice: 270,
    supplier: "AstraZeneca Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "ORS Sachet",
    genericName: "Oral Rehydration Salts",
    batchNumber: "ORS-2024-019",
    expiryDate: "2026-04-30",
    quantity: 120,
    costPrice: 5,
    salePrice: 10,
    supplier: "Martin Dow",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    name: "Zantac",
    genericName: "Ranitidine",
    batchNumber: "RAN-2024-020",
    expiryDate: "2025-10-31",
    quantity: 9,
    costPrice: 25,
    salePrice: 38,
    supplier: "GSK Pakistan",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
];

function makeSaleDate(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

const sales: SaleRecord[] = [
  {
    id: generateId(),
    items: [
      { medicineId: "seed-1", medicineName: "Panadol", quantity: 3, unitPrice: 12, lineTotal: 36 },
      { medicineId: "seed-2", medicineName: "Augmentin", quantity: 1, unitPrice: 230, lineTotal: 230 },
    ],
    totalAmount: 266,
    createdAt: makeSaleDate(0),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-4", medicineName: "Risek", quantity: 2, unitPrice: 75, lineTotal: 150 },
    ],
    totalAmount: 150,
    createdAt: makeSaleDate(0),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-6", medicineName: "Calpol", quantity: 2, unitPrice: 60, lineTotal: 120 },
      { medicineId: "seed-3", medicineName: "Brufen", quantity: 5, unitPrice: 22, lineTotal: 110 },
    ],
    totalAmount: 230,
    createdAt: makeSaleDate(1),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-9", medicineName: "Glucophage", quantity: 3, unitPrice: 42, lineTotal: 126 },
    ],
    totalAmount: 126,
    createdAt: makeSaleDate(1),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-13", medicineName: "Lipitor", quantity: 1, unitPrice: 165, lineTotal: 165 },
      { medicineId: "seed-16", medicineName: "Ventolin", quantity: 1, unitPrice: 130, lineTotal: 130 },
    ],
    totalAmount: 295,
    createdAt: makeSaleDate(2),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-12", medicineName: "Amoxil", quantity: 2, unitPrice: 70, lineTotal: 140 },
    ],
    totalAmount: 140,
    createdAt: makeSaleDate(3),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-8", medicineName: "Nexium", quantity: 2, unitPrice: 190, lineTotal: 380 },
    ],
    totalAmount: 380,
    createdAt: makeSaleDate(4),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-15", medicineName: "Folic Acid", quantity: 10, unitPrice: 5, lineTotal: 50 },
      { medicineId: "seed-19", medicineName: "ORS Sachet", quantity: 5, unitPrice: 10, lineTotal: 50 },
    ],
    totalAmount: 100,
    createdAt: makeSaleDate(5),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-18", medicineName: "Rosuvas", quantity: 2, unitPrice: 270, lineTotal: 540 },
    ],
    totalAmount: 540,
    createdAt: makeSaleDate(6),
  },
  {
    id: generateId(),
    items: [
      { medicineId: "seed-10", medicineName: "Clarinase", quantity: 3, unitPrice: 155, lineTotal: 465 },
    ],
    totalAmount: 465,
    createdAt: makeSaleDate(6),
  },
];

const expenses: Expense[] = [
  {
    id: generateId(),
    description: "Monthly Shop Rent",
    amount: 25000,
    category: "Rent",
    date: todayISO().slice(0, 7) + "-01",
    createdAt: nowISO(),
  },
  {
    id: generateId(),
    description: "Electricity Bill",
    amount: 4500,
    category: "Utilities",
    date: todayISO().slice(0, 7) + "-05",
    createdAt: nowISO(),
  },
  {
    id: generateId(),
    description: "Staff Salary — April",
    amount: 35000,
    category: "Salaries",
    date: todayISO().slice(0, 7) + "-01",
    createdAt: nowISO(),
  },
  {
    id: generateId(),
    description: "Medicine Packaging Bags",
    amount: 1200,
    category: "Supplies",
    date: todayISO().slice(0, 7) + "-08",
    createdAt: nowISO(),
  },
  {
    id: generateId(),
    description: "Refrigerator Repair",
    amount: 3500,
    category: "Maintenance",
    date: todayISO().slice(0, 7) + "-10",
    createdAt: nowISO(),
  },
];

export function seedData(): void {
  if (typeof window === "undefined") return;
  if (localStorage.getItem(STORAGE_KEYS.SEEDED)) return;

  localStorage.setItem(STORAGE_KEYS.MEDICINES, JSON.stringify(medicines));
  localStorage.setItem(STORAGE_KEYS.SALES, JSON.stringify(sales));
  localStorage.setItem(STORAGE_KEYS.EXPENSES, JSON.stringify(expenses));
  localStorage.setItem(STORAGE_KEYS.SEEDED, "true");
}
