-- =============================================================================
-- PharmaCare — Migration 012: Ledger & Accounting Module (Phase 7A)
-- File: supabase/migrations/012_ledger.sql
-- Spec: PHARMACARE_PHASE_7_LEDGER.md
--
-- Creates (in dependency order):
--   1.  accounts              — chart of accounts
--   2.  journal_entries       — immutable financial journal header
--   3.  journal_lines         — individual debit/credit lines (fully immutable)
--   4.  Immutability triggers — blocks UPDATE/DELETE on lines; blocks mutation
--                               of core financial fields on posted entries
--   5.  verify_journal_balance()   — check function (returns BOOLEAN)
--   6.  check_entry_balance()      — placeholder trigger (real check in RPC)
--   7.  borrowing_pharmacies  — neighboring pharmacy credit tracking
--   8.  borrowing_transactions — medicine + cash transactions with borrowing pharmacies
--   9.  supplier_payments     — permanent payment records for supplier balances
--   10. customer_payments     — permanent payment records for customer udhaar
--   11. exchange_rates        — currency rate history (unique per currency+date)
--   12. post_journal_entry()  — atomic RPC: generates entry_no, inserts header +
--                               lines, and enforces double-entry balance
--   13. Chart of accounts seed (23 pre-seeded accounts, is_system on core ones)
--   14. Settings seed: base_currency, multicurrency_enabled, exchange_rate_api_key
--   15. RLS policies on all new tables
--
-- Immutability guarantees (enforced at DB layer, not app layer):
--   • journal_lines: BEFORE UPDATE OR DELETE trigger raises EXCEPTION unconditionally.
--     RLS also has no UPDATE/DELETE policy — two independent guards.
--   • journal_entries (posted/reversed): BEFORE UPDATE trigger blocks changes to
--     entry_date, description, reference_*, currency, exchange_rate.
--     Allows only reversal-metadata updates (status, reversed_by, reversal_of).
--
-- User-requested constraint (not in spec):
--   CONSTRAINT no_future_dates on journal_entries prevents entry_date from being
--   more than 1 day ahead of CURRENT_DATE (evaluated at INSERT/UPDATE time).
--   The +1 day tolerance accommodates legitimate timezone edge-cases.
--
-- COGS source: stock_batches.purchase_price (NUMERIC(10,2), nullable) — confirmed
--   present in 001/008. Phase 7B will join this column when updating complete_sale().
-- =============================================================================


-- ===========================================================================
-- 1. ACCOUNTS (chart of accounts)
-- is_system = TRUE: core accounts used in auto-posting — must not be deactivated.
-- normal_balance: asset/cogs/expense = debit; liability/equity/revenue = credit.
-- parent_code self-references accounts(code) for optional hierarchy display.
-- ===========================================================================

CREATE TABLE accounts (
  id             UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  code           TEXT        NOT NULL UNIQUE,
  name           TEXT        NOT NULL,
  account_type   TEXT        NOT NULL CHECK (
                   account_type IN (
                     'asset', 'liability', 'equity', 'revenue', 'cogs', 'expense'
                   )
                 ),
  normal_balance TEXT        NOT NULL CHECK (normal_balance IN ('debit', 'credit')),
  parent_code    TEXT        REFERENCES accounts(code),
  is_system      BOOLEAN     DEFAULT FALSE,
  is_active      BOOLEAN     DEFAULT TRUE,
  description    TEXT,
  currency       TEXT        DEFAULT 'PKR',
  created_at     TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at     TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  created_by     UUID        REFERENCES profiles(id),
  is_deleted     BOOLEAN     DEFAULT FALSE,
  deleted_at     TIMESTAMPTZ
);

CREATE TRIGGER set_accounts_updated_at
  BEFORE UPDATE ON accounts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 2. JOURNAL_ENTRIES (immutable financial ledger headers)
--
-- entry_no format: JE-YYYYMMDD-XXXX (generated by post_journal_entry RPC)
-- status flow: draft → posted → reversed
--   draft   : editable, not yet committed
--   posted  : financially committed, core fields locked by trigger
--   reversed: original entry for which a reversal was created
--
-- reversed_by / reversal_of: cross-link between an entry and its reversal.
-- NO updated_at — the header is written once and only reversal metadata may change.
-- NO is_deleted — journal entries cannot be deleted, ever.
--
-- no_future_dates constraint (user requirement): entry_date may not exceed
-- CURRENT_DATE + 1 day. Evaluated at INSERT and UPDATE time.
-- ===========================================================================

CREATE TABLE journal_entries (
  id             UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  entry_no       TEXT        NOT NULL UNIQUE,
  entry_date     DATE        NOT NULL DEFAULT CURRENT_DATE,
  description    TEXT        NOT NULL,

  reference_type TEXT        CHECK (reference_type IN (
                   'sale', 'sale_return', 'purchase_order', 'grn',
                   'supplier_payment', 'customer_payment',
                   'borrowing_out', 'borrowing_in',
                   'borrowing_payment', 'expense',
                   'manual', 'opening_balance', 'adjustment'
                 )),
  reference_id   UUID,

  status         TEXT        NOT NULL DEFAULT 'posted' CHECK (
                   status IN ('draft', 'posted', 'reversed')
                 ),
  reversed_by    UUID        REFERENCES journal_entries(id),
  reversal_of    UUID        REFERENCES journal_entries(id),

  currency       TEXT        NOT NULL DEFAULT 'PKR',
  exchange_rate  NUMERIC(15,6) DEFAULT 1.000000,

  created_at     TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  created_by     UUID        REFERENCES profiles(id),

  CONSTRAINT no_self_reversal CHECK (reversed_by IS DISTINCT FROM id),
  CONSTRAINT no_future_dates  CHECK (
    entry_date <= CURRENT_DATE + INTERVAL '1 day'
  )
);

CREATE INDEX idx_journal_entries_date      ON journal_entries(entry_date);
CREATE INDEX idx_journal_entries_reference ON journal_entries(reference_type, reference_id);
CREATE INDEX idx_journal_entries_status    ON journal_entries(status);


-- ===========================================================================
-- 3. JOURNAL_LINES (individual debit/credit lines — FULLY IMMUTABLE)
--
-- amount     : in the transaction currency (same as journal_entries.currency)
-- amount_pkr : pre-calculated PKR equivalent (amount × exchange_rate)
--              Stored explicitly to avoid repeated floating-point recalculation
--              and to keep PKR-denominated reports fast.
-- party_type / party_id: optional link to a specific counterparty for
--   generating party-level ledger views without joining back to journal_entries.
--
-- NO updated_at, NO is_deleted — lines are immutable by design and trigger.
-- ===========================================================================

CREATE TABLE journal_lines (
  id          UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  entry_id    UUID          NOT NULL REFERENCES journal_entries(id),
  account_id  UUID          NOT NULL REFERENCES accounts(id),
  amount      NUMERIC(15,4) NOT NULL CHECK (amount > 0),
  direction   TEXT          NOT NULL CHECK (direction IN ('debit', 'credit')),
  amount_pkr  NUMERIC(15,4) NOT NULL CHECK (amount_pkr > 0),
  party_type  TEXT          CHECK (party_type IN ('supplier', 'customer', 'pharmacy')),
  party_id    UUID,
  description TEXT,
  created_at  TIMESTAMPTZ   DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_journal_lines_entry   ON journal_lines(entry_id);
CREATE INDEX idx_journal_lines_account ON journal_lines(account_id);
CREATE INDEX idx_journal_lines_party   ON journal_lines(party_type, party_id);


-- ===========================================================================
-- 4. IMMUTABILITY TRIGGERS
--
-- 4a. journal_lines: block ALL UPDATE and DELETE.
--     The SECURITY DEFINER post_journal_entry() only ever INSERTs lines, so
--     this trigger protects against any direct table mutation.
--
-- 4b. journal_entries: block mutation of financial fields once the entry
--     reaches 'posted' or 'reversed' status.
--     Allowed on posted entries: status → 'reversed', setting reversed_by /
--     reversal_of for the reversal workflow. Disallowed: entry_date, description,
--     reference_*, currency, exchange_rate.
-- ===========================================================================

CREATE OR REPLACE FUNCTION prevent_journal_line_mutation()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    'journal_lines are immutable — UPDATE and DELETE are not permitted (entry_id: %)',
    OLD.entry_id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER journal_lines_immutable
  BEFORE UPDATE OR DELETE ON journal_lines
  FOR EACH ROW EXECUTE FUNCTION prevent_journal_line_mutation();


CREATE OR REPLACE FUNCTION prevent_posted_entry_mutation()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.status IN ('posted', 'reversed') THEN
    IF (
      NEW.entry_date     IS DISTINCT FROM OLD.entry_date     OR
      NEW.description    IS DISTINCT FROM OLD.description    OR
      NEW.reference_type IS DISTINCT FROM OLD.reference_type OR
      NEW.reference_id   IS DISTINCT FROM OLD.reference_id   OR
      NEW.currency       IS DISTINCT FROM OLD.currency       OR
      NEW.exchange_rate  IS DISTINCT FROM OLD.exchange_rate
    ) THEN
      RAISE EXCEPTION
        'Cannot modify financial fields of a % journal entry (id: %)',
        OLD.status, OLD.id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER journal_entries_protect_posted
  BEFORE UPDATE ON journal_entries
  FOR EACH ROW EXECUTE FUNCTION prevent_posted_entry_mutation();


-- ===========================================================================
-- 5. verify_journal_balance(p_entry_id UUID) → BOOLEAN
--
-- Returns TRUE if the entry balances (|debits − credits| < 0.0001 PKR).
-- Called by server actions for pre-flight checks on manual entries.
-- The tolerance of 0.0001 accommodates floating-point rounding during
-- multi-currency conversions while being too small to mask real errors.
-- ===========================================================================

CREATE OR REPLACE FUNCTION verify_journal_balance(p_entry_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  v_debit_total  NUMERIC(15,4);
  v_credit_total NUMERIC(15,4);
BEGIN
  SELECT
    SUM(CASE WHEN direction = 'debit'  THEN amount_pkr ELSE 0 END),
    SUM(CASE WHEN direction = 'credit' THEN amount_pkr ELSE 0 END)
  INTO v_debit_total, v_credit_total
  FROM journal_lines
  WHERE entry_id = p_entry_id;

  RETURN ABS(
    COALESCE(v_debit_total,  0) -
    COALESCE(v_credit_total, 0)
  ) < 0.0001;
END;
$$ LANGUAGE plpgsql STABLE;

REVOKE ALL    ON FUNCTION verify_journal_balance(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION verify_journal_balance(UUID) TO authenticated;


-- ===========================================================================
-- 6. check_entry_balance() — placeholder trigger
--
-- The authoritative balance check happens inside post_journal_entry() which
-- accumulates debit/credit sums as it inserts each line and raises EXCEPTION
-- before the transaction commits if they diverge. A trigger cannot do this
-- check per-line-insert because not all lines have been written yet; an
-- AFTER STATEMENT trigger on journal_lines cannot inspect which entry was
-- just modified without additional bookkeeping.
--
-- This trigger is retained as a named hook point for future enhancement
-- (e.g., a DEFERRED constraint trigger). The body is intentionally a no-op.
-- ===========================================================================

CREATE OR REPLACE FUNCTION check_entry_balance()
RETURNS TRIGGER AS $$
BEGIN
  -- Balance enforcement is handled by post_journal_entry() RPC.
  -- See: supabase/migrations/012_ledger.sql — post_journal_entry()
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_entry_balance_placeholder
  AFTER INSERT ON journal_lines
  FOR EACH ROW EXECUTE FUNCTION check_entry_balance();


-- ===========================================================================
-- 7. BORROWING_PHARMACIES
--
-- current_balance: running balance maintained by the app layer and borrowing
--   transaction triggers.
--   positive = they owe us (we lent them medicine / money)
--   negative = we owe them (they lent us medicine / money)
-- ===========================================================================

CREATE TABLE borrowing_pharmacies (
  id              UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  name            TEXT          NOT NULL,
  contact_person  TEXT,
  phone           TEXT,
  address         TEXT,
  notes           TEXT,
  current_balance NUMERIC(15,4) DEFAULT 0,
  created_at      TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  updated_at      TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  created_by      UUID          REFERENCES profiles(id),
  is_active       BOOLEAN       DEFAULT TRUE,
  is_deleted      BOOLEAN       DEFAULT FALSE,
  deleted_at      TIMESTAMPTZ
);

CREATE TRIGGER set_borrowing_pharmacies_updated_at
  BEFORE UPDATE ON borrowing_pharmacies
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 8. BORROWING_TRANSACTIONS
--
-- transaction_type:
--   borrow_out  — we gave medicine to another pharmacy (their debt to us ↑)
--   borrow_in   — we received medicine from another pharmacy (our debt ↑)
--   payment_in  — they paid us cash (their debt to us ↓)
--   payment_out — we paid them cash (our debt to them ↓)
--
-- For medicine transactions: medicine_id, quantity, unit_price, total_amount.
-- For payment transactions: payment_amount, payment_notes; total_amount = payment_amount.
-- journal_entry_id: back-reference to the accounting entry created for this transaction.
-- ===========================================================================

CREATE TABLE borrowing_transactions (
  id               UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  pharmacy_id      UUID          NOT NULL REFERENCES borrowing_pharmacies(id),
  transaction_type TEXT          NOT NULL CHECK (
                     transaction_type IN (
                       'borrow_out', 'borrow_in', 'payment_out', 'payment_in'
                     )
                   ),
  medicine_id      UUID          REFERENCES medicines(id),
  medicine_name    TEXT,
  quantity         INTEGER,
  unit_price       NUMERIC(15,4),
  total_amount     NUMERIC(15,4) NOT NULL,
  payment_amount   NUMERIC(15,4),
  payment_notes    TEXT,
  journal_entry_id UUID          REFERENCES journal_entries(id),
  notes            TEXT,
  transaction_date DATE          NOT NULL DEFAULT CURRENT_DATE,
  created_at       TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  created_by       UUID          REFERENCES profiles(id),
  is_deleted       BOOLEAN       DEFAULT FALSE
);


-- ===========================================================================
-- 9. SUPPLIER_PAYMENTS
--
-- Permanent payment records — no soft-delete, no UPDATE (spec §6.1).
-- reference_no: cheque number, bank transfer reference, etc.
-- journal_entry_id: back-reference to the Accounts Payable debit entry.
-- ===========================================================================

CREATE TABLE supplier_payments (
  id               UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  supplier_id      UUID          NOT NULL REFERENCES suppliers(id),
  amount           NUMERIC(15,4) NOT NULL CHECK (amount > 0),
  payment_date     DATE          NOT NULL DEFAULT CURRENT_DATE,
  payment_method   TEXT          DEFAULT 'cash' CHECK (
                     payment_method IN ('cash', 'bank_transfer', 'cheque')
                   ),
  reference_no     TEXT,
  notes            TEXT,
  journal_entry_id UUID          REFERENCES journal_entries(id),
  created_at       TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  created_by       UUID          REFERENCES profiles(id)
);


-- ===========================================================================
-- 10. CUSTOMER_PAYMENTS (udhaar collection)
--
-- Permanent records — no soft-delete, no UPDATE.
-- Recording a customer payment also decrements customers.credit_balance
-- (handled in the recordCustomerPayment server action, Phase 7C).
-- journal_entry_id: back-reference to the Accounts Receivable credit entry.
-- ===========================================================================

CREATE TABLE customer_payments (
  id               UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id      UUID          NOT NULL REFERENCES customers(id),
  amount           NUMERIC(15,4) NOT NULL CHECK (amount > 0),
  payment_date     DATE          NOT NULL DEFAULT CURRENT_DATE,
  payment_method   TEXT          DEFAULT 'cash',
  notes            TEXT,
  journal_entry_id UUID          REFERENCES journal_entries(id),
  created_at       TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  created_by       UUID          REFERENCES profiles(id)
);


-- ===========================================================================
-- 11. EXCHANGE_RATES
--
-- One row per (currency, date) pair — UNIQUE constraint enforced.
-- rate_to_pkr: how many PKR = 1 unit of `currency` (e.g. USD→PKR ≈ 278).
-- source: 'manual' (entered by superadmin) or 'api' (fetched via API key).
-- ===========================================================================

CREATE TABLE exchange_rates (
  id          UUID          DEFAULT gen_random_uuid() PRIMARY KEY,
  currency    TEXT          NOT NULL,
  rate_to_pkr NUMERIC(15,6) NOT NULL,
  rate_date   DATE          NOT NULL,
  source      TEXT          DEFAULT 'manual',
  created_at  TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  created_by  UUID          REFERENCES profiles(id),
  UNIQUE(currency, rate_date)
);


-- ===========================================================================
-- 12. post_journal_entry() — atomic journal entry RPC
--
-- All journal entry creation (auto-posted from sales/GRN and manual entries)
-- goes through this single function.
--
-- Algorithm:
--   1. Generate entry_no (JE-YYYYMMDD-XXXX) — not transaction-safe for high
--      concurrency, acceptable for single-branch pharmacy (same caveat as POs).
--   2. INSERT journal_entries header with status='posted'.
--   3. For each line in p_lines JSONB array:
--        a. Resolve account_id from account_code.
--        b. Calculate amount_pkr = amount × exchange_rate.
--        c. INSERT journal_lines row.
--        d. Accumulate running debit/credit sums.
--   4. RAISE EXCEPTION if |debits − credits| ≥ 0.0001.
--
-- p_lines JSONB element schema:
--   {
--     "account_code": "1000",      -- required; must exist in accounts table
--     "direction":    "debit",     -- required; 'debit' | 'credit'
--     "amount":       "100.00",    -- required; positive numeric string
--     "party_type":   "customer",  -- optional; 'supplier'|'customer'|'pharmacy'
--     "party_id":     "<uuid>",    -- optional; UUID string
--     "description":  "line note"  -- optional
--   }
--
-- Returns: UUID of the created journal_entries row.
-- Raises:  'Account not found or inactive: <code>'
--          'Journal entry does not balance. Debits: X, Credits: Y'
--
-- SECURITY DEFINER: bypasses RLS so auto-posting from complete_sale() and
-- complete_grn() works regardless of the caller's role context.
-- ===========================================================================

CREATE OR REPLACE FUNCTION post_journal_entry(
  p_entry_date     DATE,
  p_description    TEXT,
  p_reference_type TEXT,
  p_reference_id   UUID,
  p_currency       TEXT,
  p_exchange_rate  NUMERIC,
  p_lines          JSONB,
  p_created_by     UUID
)
RETURNS UUID AS $$
DECLARE
  v_entry_id   UUID;
  v_entry_no   TEXT;
  v_line       JSONB;
  v_account_id UUID;
  v_debit_sum  NUMERIC(15,4) := 0;
  v_credit_sum NUMERIC(15,4) := 0;
  v_amount_pkr NUMERIC(15,4);
BEGIN
  -- Generate entry number: JE-YYYYMMDD-XXXX (daily sequence reset)
  SELECT 'JE-' || TO_CHAR(p_entry_date, 'YYYYMMDD') || '-' ||
    LPAD(
      (SELECT COUNT(*) + 1
       FROM journal_entries
       WHERE entry_no LIKE 'JE-' || TO_CHAR(p_entry_date, 'YYYYMMDD') || '-%'
      )::TEXT,
      4, '0'
    )
  INTO v_entry_no;

  -- Insert journal entry header
  INSERT INTO journal_entries (
    entry_no, entry_date, description,
    reference_type, reference_id,
    currency, exchange_rate,
    status, created_by
  ) VALUES (
    v_entry_no, p_entry_date, p_description,
    p_reference_type, p_reference_id,
    p_currency, p_exchange_rate,
    'posted', p_created_by
  ) RETURNING id INTO v_entry_id;

  -- Insert lines and accumulate balance totals
  FOR v_line IN SELECT * FROM jsonb_array_elements(p_lines) LOOP

    SELECT id INTO v_account_id
    FROM accounts
    WHERE code      = v_line->>'account_code'
      AND is_active = TRUE
      AND is_deleted = FALSE;

    IF v_account_id IS NULL THEN
      RAISE EXCEPTION 'Account not found or inactive: %', v_line->>'account_code';
    END IF;

    v_amount_pkr := (v_line->>'amount')::NUMERIC * p_exchange_rate;

    INSERT INTO journal_lines (
      entry_id, account_id,
      amount, direction, amount_pkr,
      party_type, party_id, description
    ) VALUES (
      v_entry_id,
      v_account_id,
      (v_line->>'amount')::NUMERIC,
      v_line->>'direction',
      v_amount_pkr,
      v_line->>'party_type',
      CASE WHEN (v_line->>'party_id') IS NOT NULL
           THEN (v_line->>'party_id')::UUID
           ELSE NULL
      END,
      v_line->>'description'
    );

    IF v_line->>'direction' = 'debit' THEN
      v_debit_sum  := v_debit_sum  + v_amount_pkr;
    ELSE
      v_credit_sum := v_credit_sum + v_amount_pkr;
    END IF;

  END LOOP;

  -- CRITICAL: Enforce double-entry balance before the transaction commits
  IF ABS(v_debit_sum - v_credit_sum) >= 0.0001 THEN
    RAISE EXCEPTION
      'Journal entry does not balance. Debits: %, Credits: %',
      v_debit_sum, v_credit_sum;
  END IF;

  RETURN v_entry_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

REVOKE ALL    ON FUNCTION post_journal_entry(DATE,TEXT,TEXT,UUID,TEXT,NUMERIC,JSONB,UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION post_journal_entry(DATE,TEXT,TEXT,UUID,TEXT,NUMERIC,JSONB,UUID) TO authenticated;


-- ===========================================================================
-- 13. CHART OF ACCOUNTS SEED
--
-- All 23 accounts inserted in a single statement.
-- is_system = TRUE marks accounts used in auto-posting rules (Section 4.1).
--   These accounts should not be deactivated or soft-deleted.
-- is_system = FALSE marks accounts for optional/manual use.
-- created_by is NULL — these are system seed rows, not user-created records.
-- ===========================================================================

INSERT INTO accounts
  (code,  name,                       account_type, normal_balance, is_system, description)
VALUES
  -- ASSETS (1xxx) —————————————————————————————————————————————————————————
  ('1000', 'Cash',                     'asset',   'debit',  TRUE,  'Physical cash in pharmacy'),
  ('1001', 'Cash in Hand',             'asset',   'debit',  TRUE,  'Petty cash / till'),
  ('1100', 'Accounts Receivable',      'asset',   'debit',  TRUE,  'What customers owe us (udhaar)'),
  ('1110', 'Borrowing Receivable',     'asset',   'debit',  TRUE,  'What other pharmacies owe us'),
  ('1200', 'Inventory',                'asset',   'debit',  TRUE,  'Medicine stock value'),
  ('1300', 'Prepaid Expenses',         'asset',   'debit',  FALSE, 'Advance payments'),

  -- LIABILITIES (2xxx) ———————————————————————————————————————————————————
  ('2000', 'Accounts Payable',         'liability','credit', TRUE,  'What we owe suppliers'),
  ('2010', 'Borrowing Payable',        'liability','credit', TRUE,  'What we owe other pharmacies'),
  ('2100', 'Customer Deposits',        'liability','credit', FALSE, 'Advance from customers'),

  -- EQUITY (3xxx) ————————————————————————————————————————————————————————
  ('3000', 'Owner Equity',             'equity',  'credit', TRUE,  'Capital invested'),
  ('3100', 'Retained Earnings',        'equity',  'credit', TRUE,  'Accumulated profit'),

  -- REVENUE (4xxx) ———————————————————————————————————————————————————————
  ('4000', 'Sales Revenue',            'revenue', 'credit', TRUE,  'Medicine sales'),
  ('4010', 'Other Revenue',            'revenue', 'credit', FALSE, 'Miscellaneous income'),

  -- COST OF GOODS SOLD (5xxx) ————————————————————————————————————————————
  ('5000', 'Cost of Goods Sold',       'cogs',    'debit',  TRUE,  'Purchase cost of sold medicines'),

  -- OPERATING EXPENSES (6xxx) ————————————————————————————————————————————
  ('6000', 'Operating Expenses',       'expense', 'debit',  FALSE, 'General operating costs'),
  ('6001', 'Electricity',              'expense', 'debit',  FALSE, 'Utility expenses'),
  ('6002', 'Rent',                     'expense', 'debit',  FALSE, 'Premises rent'),
  ('6003', 'Salaries',                 'expense', 'debit',  FALSE, 'Staff salaries'),
  ('6004', 'Fuel & Transport',         'expense', 'debit',  FALSE, 'Vehicle/delivery costs'),
  ('6005', 'Maintenance & Repairs',    'expense', 'debit',  FALSE, 'Equipment/premises repairs'),
  ('6006', 'Internet & Communication', 'expense', 'debit',  FALSE, 'Phone/internet bills'),
  ('6007', 'Printing & Stationery',    'expense', 'debit',  FALSE, 'Office supplies'),
  ('6008', 'Other Expenses',           'expense', 'debit',  FALSE, 'Catch-all expense account');


-- ===========================================================================
-- 14. SETTINGS SEED — multicurrency support flags
--
-- base_currency: always PKR for this pharmacy; stored for display/validation.
-- multicurrency_enabled: 'false' by default; set to 'true' to reveal exchange
--   rate fields on manual journal entries and supplier payments.
-- exchange_rate_api_key: empty by default; when set, fetchLiveRates() calls
--   exchangerate-api.com and stores results in exchange_rates table.
-- ===========================================================================

INSERT INTO settings (key, value, label) VALUES
  ('base_currency',         'PKR',   'Base Currency (always PKR for this pharmacy)'),
  ('multicurrency_enabled', 'false', 'Enable Multi-Currency Support'),
  ('exchange_rate_api_key', '',      'Exchange Rate API Key (exchangerate-api.com)')
ON CONFLICT (key) DO NOTHING;


-- ===========================================================================
-- 15. RLS POLICIES
--
-- Access model:
--   superadmin — full read + write on all ledger tables
--   admin      — read-only on all ledger tables
--   pharmacist — no access (ledger is a financial module, not clinical)
--
-- Immutability at RLS level (in addition to triggers):
--   journal_lines         — no UPDATE policy, no DELETE policy
--   borrowing_transactions — no UPDATE policy
--   supplier_payments     — no UPDATE policy, no DELETE policy
--   customer_payments     — no UPDATE policy, no DELETE policy
--
-- journal_entries UPDATE is allowed for superadmin to support:
--   draft → posted promotion and reversal metadata writes (reversed_by, status).
--   The prevent_posted_entry_mutation trigger enforces field-level immutability
--   inside those allowed UPDATE operations.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- accounts
-- ---------------------------------------------------------------------------
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "accounts_select" ON accounts FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin') AND is_deleted = FALSE);
CREATE POLICY "accounts_insert" ON accounts FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');
CREATE POLICY "accounts_update" ON accounts FOR UPDATE
  USING (get_user_role() = 'superadmin');

-- ---------------------------------------------------------------------------
-- journal_entries
-- ---------------------------------------------------------------------------
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "journal_entries_select" ON journal_entries FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin'));
CREATE POLICY "journal_entries_insert" ON journal_entries FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');
CREATE POLICY "journal_entries_update" ON journal_entries FOR UPDATE
  USING (get_user_role() = 'superadmin');

-- ---------------------------------------------------------------------------
-- journal_lines — no UPDATE, no DELETE (immutable; trigger is second guard)
-- ---------------------------------------------------------------------------
ALTER TABLE journal_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "journal_lines_select" ON journal_lines FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin'));
CREATE POLICY "journal_lines_insert" ON journal_lines FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');

-- ---------------------------------------------------------------------------
-- borrowing_pharmacies
-- ---------------------------------------------------------------------------
ALTER TABLE borrowing_pharmacies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "borrowing_pharmacies_select" ON borrowing_pharmacies FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin') AND is_deleted = FALSE);
CREATE POLICY "borrowing_pharmacies_insert" ON borrowing_pharmacies FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');
CREATE POLICY "borrowing_pharmacies_update" ON borrowing_pharmacies FOR UPDATE
  USING (get_user_role() = 'superadmin');

-- ---------------------------------------------------------------------------
-- borrowing_transactions — no UPDATE (transactions are immutable records)
-- ---------------------------------------------------------------------------
ALTER TABLE borrowing_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "borrowing_transactions_select" ON borrowing_transactions FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin') AND is_deleted = FALSE);
CREATE POLICY "borrowing_transactions_insert" ON borrowing_transactions FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');

-- ---------------------------------------------------------------------------
-- supplier_payments — no UPDATE, no DELETE (permanent records per spec §6.1)
-- ---------------------------------------------------------------------------
ALTER TABLE supplier_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "supplier_payments_select" ON supplier_payments FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin'));
CREATE POLICY "supplier_payments_insert" ON supplier_payments FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');

-- ---------------------------------------------------------------------------
-- customer_payments — no UPDATE, no DELETE
-- ---------------------------------------------------------------------------
ALTER TABLE customer_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "customer_payments_select" ON customer_payments FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin'));
CREATE POLICY "customer_payments_insert" ON customer_payments FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');

-- ---------------------------------------------------------------------------
-- exchange_rates — UPDATE allowed for superadmin (manual rate corrections)
-- ---------------------------------------------------------------------------
ALTER TABLE exchange_rates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exchange_rates_select" ON exchange_rates FOR SELECT
  USING (get_user_role() IN ('superadmin', 'admin'));
CREATE POLICY "exchange_rates_insert" ON exchange_rates FOR INSERT
  WITH CHECK (get_user_role() = 'superadmin');
CREATE POLICY "exchange_rates_update" ON exchange_rates FOR UPDATE
  USING (get_user_role() = 'superadmin');


-- =============================================================================
-- END OF MIGRATION 012
-- =============================================================================
